import React from 'react';

// Next
import Head from 'next/head';

// Components
import NavBar from './Navbar/Navbar';
import Footer from './Footer/Footer';

// Styles
import styles from './Layout.module.scss';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Proyecto Ecovivienda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
